import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Linechart from '@/components/line'
import { PieChart } from '@/components/pie'
import { DoughnutChart } from '@/components/doughnut'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Chart Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>Dashboard from Statistics Canada</h1>
      <h2>Assignment #3 displaying information provided by <Link href="https://www.statcan.gc.ca/en/start">Statistics Canada</Link></h2>
          <ul>
            <li>1. Line Chart</li>
            <li>2. Pie Chart</li>
            <li>1. Doughnut Chart</li>
          </ul>
        <div className={styles.description}>
      
          <div className={styles.text}>
          <p>This is a monthly average of the consumer price range of 
            monthly frequency of footwear and clothing products in Canada since January 2022 to July 2022.</p>
          </div>
          <div>
      <Linechart/>
      </div>
      </div>
    <br></br>
    <div className={styles.description1}>
    <div className={styles.text}>
          <p>This is an annual median percentage of the low income families based on age, sex and economic family type in Canada in the year 2015. People 18 and under fall in the largest percentage of a low income age group (16.3%), while persons aged 18-64 make up 15.7 percent of the total of the categories listed.</p>
          </div>
          <div>
      <PieChart/>
      </div>
      </div>
      <div className={styles.description}>
    <div className={styles.text}>
      <h3>Total Population of Canada in Q1 2022: 38,516,138</h3>
          <p>This is a quarterly estmate by percentage of the total population in each province and territory in Canada in the Q1 of 2022.
            Ontario makes up <strong>38.8%</strong> of Canada's population, being the largest populated province in Canada. Quebec coming in second at <strong>22.4%</strong> and B.C. coming in third with <strong>13.6%</strong>.
          </p>
          </div>
          <div>
  <DoughnutChart/>
      </div>
      </div>
      </main>
    </>
  )
}
